### ISSUE TITLE
ioctl: Resource temporarily unavailable

### ISSUE THREAD

**Issue by jungle-boogie** [farhaven/wireless#11]
Hi,

Thanks for writing `wireless`!

If wifi is already connected and wireless is re-ran, what's expected to happen?

```
$ doas wireless .config/wireless.conf
doas (jungle@jungle.my.domain) password:
Configured networks:
"network" "farhaven"
"farhaven" "network"
wireless: ioctl: Resource temporarily unavailable
```

**Comment by farhaven** [comment]
That should work, yeah. It does work on my box with an `iwm`. Does the same error appear if you do an `ifconfig $device scan` while the wifi is connected?

**Comment by jungle-boogie** [comment]
The scan works, but takes quite awhile - about 30 seconds.
It seems like `doas wireless .config/wireless.conf` also takes about the same amount of time.

**Comment by farhaven** [comment]
I just pushed a change that might fix this by doing an `ifconfig $dev down && ifconfig $dev up` before scanning. Seems to be necessary with -current on my laptop. Does it work for you?

**Comment by just22** [comment]
Hello,
same problem here with -current and version in ports (v3), iwn device.
I do confirm that, after applying the modifications as per commit "Do an ifconfig down/up dance before scanning", it works flawlessly even when the wifi is already connected.

Do you mind to bump a new version?

**Comment by farhaven** [comment]
Yup, sounds good. I'll close this bug later tonight when I released a new version. I'll also push an updated port to ports@.

**Comment by farhaven** [comment]
I just created a new release and sent a port update to `ports@`.

**Comment by jungle-boogie** [comment]
I confirm your fix works! So sorry for not follow up sooner!
