### ISSUE TITLE
String parsing is broken

### ISSUE THREAD

**Issue by farhaven** [farhaven/wireless#2]
This will yield a syntax error:

```wpa "foo" "bar ?"```

[This](https://stackoverflow.com/questions/5418181/flex-lex-encoding-strings-with-escaped-characters) might be useful.

**Comment by farhaven** [comment]
Done. b7f9773 fixes this by importing `bgpd`'s parser.

**Comment by jggimi** [comment]
On 2016-04-05 13:38, Gregor Best wrote:

> Done. b7f9773 [1] fixes this by importing bgpd's parser. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub [2]

Thanks, Gregor!  I'll play with it this evening, after $DAYJOB. :) 

  

Links:
------
[1]
https://github.com/farhaven/wireless/commit/b7f9773bc2d066ed41a46a63ab4df3f3c36864e4
[2] https://github.com/farhaven/wireless/issues/2#issuecomment-205912768
