### ISSUE TITLE
dhclient doesn't connect

### ISSUE THREAD

**Issue by jungle-boogie** [farhaven/wireless#7]
Hi,

Thanks for writing this great tool to help connect to wifi networks a bit easier and quicker.

I'm using i386 snapshot from the 3rd of May without any special/additional configurations to the OS, and I can't seem to get dhclient to connect as expected. I can use hostname.interface and ifconfig to connect to the network, though.

wireless.conf:
```
# I'm a comment!

mynwid = "wifinetwork"
mypw = "passwordxxx"

# include "wireless.conf.local"

device urtw0
verbose
debug

open $mynwid

wpa nw1 $mypw
#wpa nw2 $mypw
```

```
$ ifconfig urtw0 media
urtw0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        lladdr 00:c0:ca:4f:7a:6e
        index 5 priority 4
        groups: wlan
        media: IEEE802.11 autoselect (DS1 mode 11g)
        status: no network
        ieee80211: nwid wifinetwork bssid 64:00:00:42:d6:80 100dBm
        supported media:
                media autoselect
                media autoselect mediaopt monitor
                media autoselect mode 11b
                media autoselect mode 11b mediaopt monitor
                media autoselect mode 11g
                media autoselect mode 11g mediaopt monitor
```

So this looks like your utility setup the connection and what's why we see the nwid name.

```
$ doas dhclient urtw0
urtw0: no link ........... sleeping
```

What am I doing wrong to get this working as explained in the readme?

**Comment by jungle-boogie** [comment]
I got it working! I was over complicating the tool and had a wrong config file.
Exactly this can get me connected to the network:
`wpa "wifinetwork" "passwordxxx"`

Thanks!

**Comment by farhaven** [comment]
That probably means I need to write a proper manpage :smile: The example configuration file just crams everything there is in it, which makes it really confusing.

**Comment by jungle-boogie** [comment]
> which makes it really confusing.

I only got confused because I didn't think it was so simple!

A manpage about the macros would be great, though.
